#Do not touch this
version: 1.3
options:
  #The prefix that will be shown throughout the plugin, and in the %prefix% placeholders
  prefix: "&8[&dStaff&8]"
  #Do we hook into essentials API and enable features?
  essentials: true
  #Settings for when player is in staff godmode
  god:
    #What we disable for gods
    disableDamage: true
    disableHunger: true
    disableDeath: true
    #Do we display message when played died?
    messageGod: true
    #Do we send a server wide message when the player dies?
    messageEveryone: true
    #Do we message the killer?
    messageKiller: true
    #Message to the goded player when they die
    messageToGod: "%prefix% &cYour power keeps you alive, but at what cost?"
    #Message sent to all players on the server
    messageToEveryone: "&d%player% refuses to fall..."
    #If the killer was a player, send this message
    messageToAttacker: "&cDid you really think you could slay a god %player%...? You...?"
#Added in 1.3, when essentials in enabled
essentials:
  #Do we put afk staff into vanish?
  vanishAfkStaff: true
  #Do we disable chest open animations for vanished players?
  silentChestStaff: true
#Added in 1.2, staff ranks of the network
#The left side is the plugin message that will always be sent, the right is the real rank on the spigot server
ranks:
  gamemaster: 'GameMaster'
  gameengineer: 'GameEngineer'
  dungeonmaster: 'DungeonMaster'
  gamemanager: 'GameManager'
  gamekeeper: 'GameKeeper'
  gamearchitect: 'GameArchitect'
  
messages:
  #Displayed when made an operator with /opme. Placeholders: %prefix%
  madeOp: "%prefix% &aYou've been made a server operator."
  #Displayed when /deopme is ran and they've been deopped
  madeDeop: "%prefix% &aYou are no longer a server operator."
  #Displayed when /deopme is ran, and they're not op
  alreadyDeop: "%prefix% &cYou are not a server operator."
  #Displayed when a player is made a god with /godme
  madeGod: "%prefix% &dImmortality &aenabled&d."
  #Displayed when player has disabled god
  madeMortal: "%prefix% &dImmortality &cdisabled&d."
  #Displayed when user is already an operator. Placeholders: %prefix%
  alreadyOp: "%prefix% &cYou are already an operator."
  #This is always be displayed when a user is denied permission spigotside. Placeholders: %prefix%
  nopermission: '&cYou do not have permission to do this.'
  #Called when configuraiton is reloaded
  reloadedConfig: "%prefix% &aYou have reloaded the config."