name: Staff
version: 1.3
main: me.Devee1111.Spigot.StaffPowers
author: Devee1111
commands:
  testspigot:
    description: This is just a little test to see if it's active.
  staffreloadspigot:
    description: Reload the staff plugin in current spigot server.
    